# Programs
bind = $mainMod, W, exec, firefox
bind = $mainMod, N, exec, [float;center;size 1200 900;workspace unset] kitty ncmpcpp

# Screenshots
# Screenshot a window
bind = $mainMod, PRINT, exec, hyprshot -m window
# Screenshot a monitor
bind = , PRINT, exec, hyprshot -m region -z
# Screenshot a region
bind = SHIFT, PRINT, exec, hyprshot -m active
# Lock Screen
# bind = $mainMod, L, exec, hyprlock
bind = $mainMod CTRL, L, exec, sleep 1 && hyprctl dispatch dpms off

# Task manager
bind = CTRL SHIFT, Escape, exec, [float;center;size 1200 900;workspace unset] kitty htop

# Clipboard manager
bind = $mainMod, V, exec, [group deny;float;dimaround;stayfocused] copyq menu

bind = ALT, Tab, exec, ~/.config/hypr/scripts/switch.py

bind = $mainMode, G, togglegroup
bind = $mainMode, Tab, changegroupactive, f
bind = $mainMode SHIFT, Tab, changegroupactive, b
